apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    app: MyApp
spec:
  containers:
  - name: mysite
    image: akash1234karma/dockerfile
    ports:
     - containerPort: 8080
     
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
   - protocol: TCP
     port: 80
     nodePort: 30003
