apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs 
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: akash1234karma/dockerfile:$BUILD_NUMBER
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32105
